# Generated by Django 4.0 on 2024-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='bhatkal', max_length=200),
            preserve_default=False,
        ),
    ]
